apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: integration-runner-policy-reader
  namespace: {{ .Values.release.targetNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konflux-integration-runner
subjects:
  - kind: ServiceAccount
    name: konflux-integration-runner
    namespace: {{ .Values.namespace }}
