{{- if .Values.users }}
{{- range .Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-konflux-admin
  namespace: {{ $.Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konflux-admin-user-actions
subjects:
- kind: User
  name: {{ . }}@konflux.dev
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
