{{- if .Values.signing.enableSigning }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: signing-key-generator
  namespace: {{ .Values.release.targetNamespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
{{- end }}
