{{- if .Values.signing.enableSigning }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-signing-key-reader
  namespace: {{ .Values.release.targetNamespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["release-signing-key"]
  verbs: ["get"]
{{- end }}
