{{- if and .Values.createTargetNamespace .Values.targetUsers .Values.release.targetNamespace }}
{{- range .Values.targetUsers }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-konflux-admin
  namespace: {{ $.Values.release.targetNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konflux-admin-user-actions
subjects:
- kind: User
  name: {{ . }}@konflux.dev
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
