{{- if and .Values.release.trustedArtifacts.username .Values.release.trustedArtifacts.password }}
apiVersion: v1
kind: Secret
metadata:
  name: trusted-artifacts-secret
  namespace: {{ .Values.release.targetNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.release.trustedArtifacts.ociStorage .Values.release.trustedArtifacts.username .Values.release.trustedArtifacts.password (printf "%s:%s" .Values.release.trustedArtifacts.username .Values.release.trustedArtifacts.password | b64enc) | b64enc }}
{{- end }}
