{{- if .Values.signing.enableSigning }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: signing-key-generator
  namespace: {{ .Values.release.targetNamespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
{{- end }}
